version: '3.8'
services:
  monitor:
    build : .
    container_name: server-monitor
    ports:
      - "5004:5004"
    env_file:
      - .env
    restart: always
    cap_add:
      - NET_RAW
    network_mode: "host"
    
