version: '3.8'

services:
  ping-monitoring:
    build: .
    container_name: ping-monitoring
    ports:
      - "5004:5004"
    env_file:
      - .env
    depends_on:
      - fluentd
    networks:
      - monitoring-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  monitoring-net:
    driver: bridge
